# Generated by Django 5.1.2 on 2024-10-11 17:00

import django_extensions.db.fields
import picpay.account.entities
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_number', models.CharField(max_length=14, unique=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ACCOUNT',
                'constraints': [models.UniqueConstraint(fields=('document_number', 'email'), name='unique_account')],
            },
            bases=(models.Model, picpay.account.entities.AccountEntity),
        ),
    ]
