# Generated by Django 5.1.2 on 2024-10-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_wallet', to='wallet.wallet'),
        ),
    ]
